# dummy_hcd Makefile

obj-y += dummy_hcd.o

# Original Makefile:
# obj-m := dummy_hcd.o
# KDIR := /lib/modules/$(shell uname -r)/build
# PWD := $(shell pwd)

# default:
# 	$(MAKE) -C $(KDIR) M=$(PWD) SUBDIRS=$(PWD) modules
