#!/bin/sh
#
# Start watchdog
#

case "$1" in
 start)
	echo "Starting watchdog..."
	modprobe interrupt_test
	;;
  stop)
  	modprobe -r interrupt_test
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
