#!/bin/sh
#
# Start driver at boot
#

case "$1" in
  start)
	echo "Starting TOTP SPDM driver..."
	modprobe totp_spdm_driver
	;;
  stop)
  	modprobe -r totp_spdm_driver
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
